version: 2
jobs:
  build:
    docker:
      - image: node:8@sha256:deb6287c3b94e153933ed9422db4524d2ee41be00b32c88a7cd2d91d17bf8a5e

    working_directory: ~/slashhandler

    steps:
      - checkout:
          post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

      - restore_cache:
          keys:
            - slashhandler-node8-{{ checksum "package.json" }}
            - slashhandler-node8-
      - restore_cache:
          keys:
            - sonar-cache

      - run: npm install --quiet
      - run: npm i -g sonarqube-scanner --quiet
      # - run:
      #     name: Set Environment Variables
      #     command: |
      #       echo "export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")" >> $BASH_ENV
            # source $BASH_ENV

      - save_cache:
          key: slashhandler-node8-{{ checksum "package.json" }}
          paths:
            - ~/slashhandler/node_modules

      - run: npm run lint

      - run: npm run test:ci

      - run:
          name: Push Code Coverage
          command: bash <(curl -s https://codecov.io/bash) || true
          environment:
            CODECOV_TOKEN: 12625a2c-a74b-4756-a8e3-d8a63b52ef53

      # store test reports
      - store_test_results:
          path: coverage

      - run:
          name: sonar
          command: sonar-scanner -Dsonar.projectVersion=$CIRCLE_BUILD_NUM -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN

      - save_cache:
          paths:
            - ~/.sonar
          key: sonar-cache

      - deploy:
          name: Release
          command: npm run release